parameters:
#    acme_address_book.example.class: Acme\AddressBookBundle\Example

services:
#    acme_address_book.example:
#        class: %acme_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
